### ISSUE TITLE
This isn't an issue, this is a thank you

### ISSUE THREAD

**Issue by rgarner** [z8i/klogg#1]
I've got a replacement Klimalogg Pro in front of me and I no longer have a Windows machine, so I've fired up a local Python and am building a dashboard in Flask.

This Just Works and it's obvious it took a good deal of effort (was about to port to Ruby till I saw the size of it), so I want to say thanks.

Thanks. I appreciate you.

**Comment by z8i** [comment]
Thanks for the comment! Did you notice, that the original work was done by [weex-klimalogg by matthewwall](https://github.com/matthewwall/weewx-klimalogg), maybe this code suits your needs even better, make sure to take a look ;-)

**Comment by rgarner** [comment]
I did, thanks! It's just that weewx wasn't what I wanted – I wanted an API to build something personal, and this was closer. It's pretty niche, and I'm glad it exists. Thanks again.
